name: chai-1

channels:
  - pytorch
  - conda-forge
  - nvidia/label/cuda-11.8.0
  - bioconda

dependencies:
  - python>=3.10
  - pytorch=2.3.1=*cuda*
  - pytorch-cuda=11.8
  - nvidia/label/cuda-11.8.0::cuda

  - fsspec
  - biopython>=1.83
  - rdkit=2023.9.5
  - biotite
  - modelcif>=1.0
  - ihm
  - gemmi=0.6.3

  - joblib
  - numpy>=1.21, <2.0
  - numba
  - einops=0.8
  - scipy
  - transformers=4.44
  # - ipykernerl=6.27
  # - seaborn
  # - matplotlib

  - pandas=2.1
  - pyarrow
  - pandera

  # # dev
  # - mypy
  # - pytest
  # - pre-commit

  # # types/stubs are required by mypy
  # - pandas-stubs
  # - types-pyyaml
  # - types-tqdm
  # - typing-extensions
  # - types-requests  

  - typer=0.12
  - jaxtyping>=0.2.25
  - beartype>=0.18

  - tqdm

  - pip
  - pip:
      - tmtools>=0.0.3
      - antipickle==0.2.0
